export const logInButton = '.login-button__iconButton-3m';
export const logInButtonText = 'text=Войти через Яндекс ID';
export const userNameInputLocator = 'input[name="login"]';
export const logInButtonElemLocator = 'button[type="submit"]';
export const errorMessageLocator = '.Textinput-Hint';
export const searchInputLocator = 'input[type="text"]';
export const videoItemsLocator = '.feed__row';
export const videoPlayerLocator ='.video-player';
export const videoTitleLocator = '.video-player h1';
export const navigationBarLocator = "//*[@class='navigation-tab-list__list-2f']";
export const  BASE_URL = "https://dzen.ru";
export const VIDEO_URL = "https://dzen.ru/video";
